server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_db
    username: root
    password: CHAT_DB
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

  application:
    name:
      EMPLOYEE-SERVICE